### ISSUE TITLE
Общая доска с результатами тестирования

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Projects#1]
По каждому проекту показывать, когда последний раз проект был собран, за сколько времени, если были тесты - процент прошедших, и так далее
Для абсолютного большинства проектов настроен CI/CD пайплайн, так что показать эту информацию можно и нужно

В перспективе эта информация может перетечь на лендинг за счет публикации API с этой информации

**Comment by Suput** [comment]
К какой версии это адресовано? В версии 2 (текущей) мы отказались от ГХ репозиториев. То есть их можно прикрепить как сторонние ссылки.  
Если очень нужно, этот функционал можно возобновить

**Comment by CAPCHIK** [comment]
Можно подумать про этот функционал в будущем, когда будем прописывать, если будем, связь репов и проектов, когда PR может закрыть задачу и тд. На данный момент Issue не актуален
