### ISSUE TITLE
Аутентификация для WebHook

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Projects#14]
Сейчас маршрут /api/projects/update не защищен аутентификацией

Необходимо реализовать метод, описанный в документации GH, для защиты этого маршрута
https://docs.github.com/en/free-pro-team@latest/developers/webhooks-and-events/securing-your-webhooks

Как вариант - могу предложить использовать билиотеку https://github.com/go-playground/webhooks для обработки webhook, она же работает с секретом, и предоставляет удобный  api

**Comment by 0B1t322** [comment]
Issue адресован к версии v1 и не нуждается в версии v2.
