### ISSUE TITLE
Публичное API для лендинга

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Projects#16]
Необходимо организовать публично доступное API, которое будет раздавать информацию о существующих проектах в лаборатории для лендинга rtuitllab.dev

Соответственно необходимы как  минимум два endpoint-а:

## Возврат списка проектов c с полями
* название
* preview изображение
* дата релиза
* теги (VR/AR/Frontend и тд)
Который обеспечивает отображение первичной информации
![image](https://user-images.githubusercontent.com/12235437/104812006-5264f080-5810-11eb-8ede-f31af24fb1e1.png)

## возврат подробной информации по конкретному проекту
* Текстовка - описание
* Список медиа материалов (изображения, видео)
* Перечисление используемых технологий
* Перечисление разработчиков
* Перечисление ссылок на исходный код (при наличии)
* Дата последнего релиза
Должен обеспечивать отображение страницы о проекте
![image](https://user-images.githubusercontent.com/12235437/104812053-9e179a00-5810-11eb-9de6-0431824fb6c7.png)

## Пример модели данных на сайте
Сейчас информация на сайте захардкожена в исходном коде, и представлена [тут](https://github.com/RTUITLab/Landing-Front/blob/01056789809d5bee30174c573e0d2eee2c78f9fa/src/modules/projects/src/projectsData.js)
Пример информации о ITLab

https://github.com/RTUITLab/Landing-Front/blob/01056789809d5bee30174c573e0d2eee2c78f9fa/src/modules/projects/src/projectsData.js#L35-L50

Данный формат можно использовать как начальный, для выстраивания публичного API

За комментариями по необходимому и удобному для использования формату необходимо обращаться к @kekboxer, ибо он отвечает за лендинг

**Comment by 0B1t322** [comment]
Endpoint для получения компактных лендингов, должен отдавать сразу все лендинги или подгрузкой чанков?

**Comment by 0B1t322** [comment]
Endpoint для получения компактных лендингов, должен отдавать сразу все лендинги или подгрузкой чанков?

**Comment by 0B1t322** [comment]
Endpoint для получения компактных лендингов, должен отдавать сразу все лендинги или подгрузкой чанков?

**Comment by 0B1t322** [comment]
Endpoint для получения компактных лендингов, должен отдавать сразу все лендинги или подгрузкой чанков?

**Comment by 0B1t322** [comment]
Endpoint для получения компактных лендингов, должен отдавать сразу все лендинги или подгрузкой чанков?

**Comment by 0B1t322** [comment]
Вроде как пока что отошли от API лендинга с проектов, поэтому закрываю issue
