### ISSUE TITLE
Общая доска с текущими задачами

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Projects#2]
Нужно бы сделать отдельную страницу со всеми текущими Issue
Для грамотности на них надо всегда вешать label, к какой теме они относятся, Back end, Frontend, VR, и так далее
В итоге если человек не знает, чем ему заняться, например, может зайти в эту доску задач, выбрать что ему интересно и помочь кому-то с проектом

**Comment by CAPCHIK** [comment]
И логично на этих задачах сразу показывать теги не только самих issue, но и теги проектов из данного пункта https://github.com/RTUITLab/ITLab-Projects/issues/3

**Comment by 0B1t322** [comment]
Issue является неактуальным для версии v2
