### ISSUE TITLE
Теги проектов

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Projects#3]
У каждого проекта необходимо вывешивать список тегов, про то, что в себе содержит данный проект
Пример таких тегов
C#,ASP.NET Core 3.1,ASP.NET Core,Redid,Postgres,Rabbit
Так, проект описывает, какие технологии в нем применяются
На выходе можно иметь представление, что популярно, плюс, эта же информация по ом может отображаться на лендинге

**Comment by komarb** [comment]
implemented
