### ISSUE TITLE
Get all versions

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/ITLab-Projects#49]
Необходим endpoint для получения всех текущих версий, с параметром, отдавать все, или отдавать только текущие

При запросе должен проверяться клейм админа проектов

**Comment by 0B1t322** [comment]
Что значит "Текущие" версии?

**Comment by CAPCHIK** [comment]
Те, что прикладываются к проектам на странице проектов, то есть актуальные, которые делаются сейчас
