### ISSUE TITLE
Latest version comes first instead of the highest

### ISSUE THREAD

**Issue by Suput** [RTUITLab/ITLab-Projects#51]
_Move issue from Front to Back part._  

Cначала заполнили информацию по версии 0.2.0, потом добавили информацию по версии 0.1.0.  
Последняя добавленная версия (0.1.0) отображается в списке вместо самой высокой версии (0.2.0).  

![image](https://user-images.githubusercontent.com/40500378/141946232-22936ae0-8a23-4c08-b9da-f17e42d1c528.png)

__Предложение__: выставлять информацию о проекте не по последней добавленной версии, а по строке версии проекта

**Comment by 0B1t322** [comment]
Выставлять версию по имени - не совсем удачное решение так как имя не гарантировано вида v x.x.x. Потому фильтрация будет по дате мягкого дедлайна, что гарантирует что версии созданные для отражение прошлых версий не будут появляться как "Последняя версия"

**Comment by Suput** [comment]
На будущее. Можно называть ветки через слеш и тогда они будут складываться красиво в папки

На фото ниже пример, как это будет выглядеть. Таким образом можно создать папки "features" и "fixes", например. Ну или как тебе в голову придёт
![image](https://user-images.githubusercontent.com/40500378/141954055-0cc01f1b-c94e-41c2-8555-28c550885e4c.png)

**Comment by Suput** [comment]
@0B1t322 вроде да, но вроде нет
Я вижу список - последняя версия "Новая версия" (у неё дедлайн далеко очень), но открывая этот проект, я попадаю на первую версию
Может быть это потому, что у неё дедлайн ооооочень далеко и есть версии, которые ближе, и которые быстрее должны выполнится?
![image](https://user-images.githubusercontent.com/40500378/141958247-28239ea3-217e-468c-836b-83090305e739.png)
![image](https://user-images.githubusercontent.com/40500378/141958464-45228e88-82d1-4065-8162-950cabd1be74.png)

Пришла в голову такая ужасная идея: взять все дедлайны мягкие, отсортировать их от ранней к поздней, показывать ту, которая ближе к реальному времени  

### Пример реализации:
Есть проект с тремя версиями:
"Первая версия". Мягкий дедлайн: 18.10.2021. Жёсткий дедлайн: 31.10.2021  
"Вторая версия". Мягкий дедлайн: 18.11.2021. Жёсткий дедлайн: 30.11.2021  
"Третья версия". Мягкий дедлайн: 18.11.2021. Жёсткий дедлайн: 31.12.2021  

Соответственно, текущая дата 16.11.2021. Значит "Первая версия" уже прошла, "Вторая версия" идёт сейчас, а "Третья версия" будет позже. -> Актуальная версия "Вторая версия", потому что она по мягкому дедлайну ближе всего к текущей дате.
Тогда на фронт надо отправлять все три версии, но сказать ему какую версию показывать


### Пока писал эту дичь, возник вопрос: "А будет ли кто-то создавать версию заранее?"  
Так или иначе - посмотри две картинки выше. На общем списке версия одна, при открытии проекта, версия другая

**Comment by 0B1t322** [comment]
При открытии проекта, какая версия открывается это решает уже фронт.
https://github.com/RTUITLab/ITLab-Projects-Front/blob/fce5ab8c61a241589dda6b0204ed146ff384faae/src/components/VersionComponent/VersionComponent.js#L45

Судя по этим строчкам берется первая версия из списка.

**Comment by CAPCHIK** [comment]
Выходит, или тебе на сервере сортировать список надо по дедлайну, это логично, и фронт работать будет верно
Плюс - @FineBot стоит брать не первый элемент из списка, а из специального поля `last_version`
Так у нас и фронт и бек будут согласованы

**Comment by 0B1t322** [comment]
Добавлю сортировку в список версий в том числе

**Comment by 0ReC0** [comment]
![image](https://user-images.githubusercontent.com/41593670/142035252-a4525eeb-174b-4b1c-8d0a-bea0d5ec91d8.png)
## На всех проектах все еще показывается неверно
@Suput @0B1t322

**Comment by Suput** [comment]
> ## На всех проектах все еще показывается неверно
> @Suput @0B1t322

Потому что не слиты PR. Если прочитать все сообщения тут, то станет ясно, что функционал есть и лежит только на ответственности Фронт части. А это issue Бэк части. Для Бэк части issue закрыт
